### ISSUE TITLE
REQUEST : Better result viewing

### ISSUE THREAD

**Issue by rodnem** [romannurik/Figma-Contrast#11]
Hello
Love your contrast checker (sketch or figma)
but in figma the preview is too small
I need either to 
- be able to resize the result viewer
- export the result as bitmap or svg

Thank you

**Comment by romannurik** [comment]
Yes yes, good point. Zooming/resizing would be useful.

**Comment by romannurik** [comment]
Zooming/resizing has been supported for a few months now - closing
