### ISSUE TITLE
Plugin window resize bug

### ISSUE THREAD

**Issue by kiralaktionov** [romannurik/Figma-Contrast#15]
When I try drag and drop the plugin window, it won't allow me. The way resizing works is that I have to click the resize corner, and then move my pointer, keeping it within that corner, clicking to finish resize. Please look into it.
Neat product btw, thank you!

**Comment by romannurik** [comment]
Hi! This is currently due to a limitation in the Figma plugin API. There are some additional UI tweaks we can make (e.g. a size menu in addition to a drag grip) but there's no clean outright solution at the moment.

**Comment by romannurik** [comment]
Fixed!
